#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT_PERCENT = 5,
  aux_sym_template_token1 = 6,
  aux_sym_template_token2 = 7,
  anon_sym_PERCENT_GT = 8,
  anon_sym_LT_PERCENT_POUND = 9,
  anon_sym_LT = 10,
  anon_sym_SLASH_GT = 11,
  anon_sym_LT_SLASH = 12,
  anon_sym_EQ = 13,
  sym_attribute_name = 14,
  sym_attribute_value = 15,
  anon_sym_SQUOTE = 16,
  aux_sym_quoted_attribute_value_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_attribute_value_token2 = 19,
  sym_text = 20,
  sym__start_tag_name = 21,
  sym__script_start_tag_name = 22,
  sym__style_start_tag_name = 23,
  sym__end_tag_name = 24,
  sym_erroneous_end_tag_name = 25,
  sym__implicit_end_tag = 26,
  sym_raw_text = 27,
  sym_comment = 28,
  sym_fragment = 29,
  sym_doctype = 30,
  sym__node = 31,
  sym_element = 32,
  sym_template = 33,
  sym_comment_directive = 34,
  sym_script_element = 35,
  sym_style_element = 36,
  sym_start_tag = 37,
  sym_script_start_tag = 38,
  sym_style_start_tag = 39,
  sym_self_closing_tag = 40,
  sym_end_tag = 41,
  sym_erroneous_end_tag = 42,
  sym_attribute = 43,
  sym_quoted_attribute_value = 44,
  aux_sym_fragment_repeat1 = 45,
  aux_sym_start_tag_repeat1 = 46,
  aux_sym_quoted_attribute_value_repeat1 = 47,
  aux_sym_quoted_attribute_value_repeat2 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT_PERCENT] = "<%",
  [aux_sym_template_token1] = "template_token1",
  [aux_sym_template_token2] = "template_token2",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_LT_PERCENT_POUND] = "<%#",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_template] = "template",
  [sym_comment_directive] = "comment",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_quoted_attribute_value_repeat2] = "quoted_attribute_value_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [aux_sym_template_token1] = aux_sym_template_token1,
  [aux_sym_template_token2] = aux_sym_template_token2,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_POUND,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_template] = sym_template,
  [sym_comment_directive] = sym_comment,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_quoted_attribute_value_repeat2] = aux_sym_quoted_attribute_value_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_template_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '\'') ADVANCE(39);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\'') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(39);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 16:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_template_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_template_token2);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_template_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_template_token2);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '%') ADVANCE(26);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 18, .external_lex_state = 2},
  [2] = {.lex_state = 18, .external_lex_state = 3},
  [3] = {.lex_state = 18, .external_lex_state = 3},
  [4] = {.lex_state = 18, .external_lex_state = 3},
  [5] = {.lex_state = 18, .external_lex_state = 3},
  [6] = {.lex_state = 18, .external_lex_state = 2},
  [7] = {.lex_state = 18, .external_lex_state = 3},
  [8] = {.lex_state = 18, .external_lex_state = 2},
  [9] = {.lex_state = 18, .external_lex_state = 3},
  [10] = {.lex_state = 18, .external_lex_state = 3},
  [11] = {.lex_state = 18, .external_lex_state = 3},
  [12] = {.lex_state = 18, .external_lex_state = 3},
  [13] = {.lex_state = 18, .external_lex_state = 3},
  [14] = {.lex_state = 18, .external_lex_state = 3},
  [15] = {.lex_state = 18, .external_lex_state = 2},
  [16] = {.lex_state = 18, .external_lex_state = 3},
  [17] = {.lex_state = 18, .external_lex_state = 3},
  [18] = {.lex_state = 18, .external_lex_state = 3},
  [19] = {.lex_state = 18, .external_lex_state = 3},
  [20] = {.lex_state = 18, .external_lex_state = 3},
  [21] = {.lex_state = 18, .external_lex_state = 3},
  [22] = {.lex_state = 18, .external_lex_state = 3},
  [23] = {.lex_state = 18, .external_lex_state = 3},
  [24] = {.lex_state = 18, .external_lex_state = 2},
  [25] = {.lex_state = 18, .external_lex_state = 3},
  [26] = {.lex_state = 18, .external_lex_state = 2},
  [27] = {.lex_state = 18, .external_lex_state = 2},
  [28] = {.lex_state = 18, .external_lex_state = 2},
  [29] = {.lex_state = 18, .external_lex_state = 3},
  [30] = {.lex_state = 18, .external_lex_state = 2},
  [31] = {.lex_state = 18, .external_lex_state = 2},
  [32] = {.lex_state = 18, .external_lex_state = 2},
  [33] = {.lex_state = 18, .external_lex_state = 2},
  [34] = {.lex_state = 18, .external_lex_state = 3},
  [35] = {.lex_state = 18, .external_lex_state = 2},
  [36] = {.lex_state = 18, .external_lex_state = 2},
  [37] = {.lex_state = 18, .external_lex_state = 2},
  [38] = {.lex_state = 18, .external_lex_state = 2},
  [39] = {.lex_state = 18, .external_lex_state = 2},
  [40] = {.lex_state = 18, .external_lex_state = 2},
  [41] = {.lex_state = 2, .external_lex_state = 2},
  [42] = {.lex_state = 5, .external_lex_state = 4},
  [43] = {.lex_state = 4, .external_lex_state = 2},
  [44] = {.lex_state = 2, .external_lex_state = 2},
  [45] = {.lex_state = 2, .external_lex_state = 2},
  [46] = {.lex_state = 5, .external_lex_state = 4},
  [47] = {.lex_state = 5, .external_lex_state = 4},
  [48] = {.lex_state = 5, .external_lex_state = 4},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 4, .external_lex_state = 2},
  [51] = {.lex_state = 2, .external_lex_state = 2},
  [52] = {.lex_state = 2, .external_lex_state = 2},
  [53] = {.lex_state = 4, .external_lex_state = 2},
  [54] = {.lex_state = 5, .external_lex_state = 4},
  [55] = {.lex_state = 4, .external_lex_state = 2},
  [56] = {.lex_state = 5, .external_lex_state = 4},
  [57] = {.lex_state = 5, .external_lex_state = 2},
  [58] = {.lex_state = 5, .external_lex_state = 2},
  [59] = {.lex_state = 5, .external_lex_state = 2},
  [60] = {.lex_state = 5, .external_lex_state = 2},
  [61] = {.lex_state = 1, .external_lex_state = 2},
  [62] = {.lex_state = 5, .external_lex_state = 2},
  [63] = {.lex_state = 1, .external_lex_state = 2},
  [64] = {.lex_state = 5, .external_lex_state = 4},
  [65] = {.lex_state = 4, .external_lex_state = 2},
  [66] = {.lex_state = 5, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 5, .external_lex_state = 4},
  [71] = {.lex_state = 4, .external_lex_state = 2},
  [72] = {.lex_state = 5, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 6},
  [74] = {.lex_state = 2, .external_lex_state = 2},
  [75] = {.lex_state = 2, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 5},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 5},
  [79] = {.lex_state = 6, .external_lex_state = 2},
  [80] = {.lex_state = 6, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 5},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 5, .external_lex_state = 2},
  [84] = {.lex_state = 5, .external_lex_state = 2},
  [85] = {.lex_state = 5, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 7},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 6, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 5},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 6, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 8},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 16, .external_lex_state = 2},
  [114] = {.lex_state = 16, .external_lex_state = 2},
  [115] = {.lex_state = 17, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 9},
  [117] = {.lex_state = 17, .external_lex_state = 2},
  [118] = {.lex_state = 16, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 8},
  [121] = {.lex_state = 0, .external_lex_state = 9},
  [122] = {.lex_state = 16, .external_lex_state = 2},
  [123] = {.lex_state = 16, .external_lex_state = 2},
  [124] = {.lex_state = 16, .external_lex_state = 2},
  [125] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [aux_sym_template_token1] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(119),
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_template] = STATE(8),
    [sym_comment_directive] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(77),
    [sym_style_start_tag] = STATE(76),
    [sym_self_closing_tag] = STATE(15),
    [sym_erroneous_end_tag] = STATE(8),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT_PERCENT] = ACTIONS(9),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_LT_SLASH] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(18), 1,
      sym_end_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [51] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_text,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(23), 1,
      sym_end_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(2), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [102] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      sym_text,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_end_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [153] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(23), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(41), 1,
      sym_text,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_end_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(4), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [204] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_LT_BANG,
    ACTIONS(50), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(53), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(56), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_SLASH,
    ACTIONS(62), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(77), 1,
      sym_script_start_tag,
    STATE(6), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [252] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym__implicit_end_tag,
    ACTIONS(65), 1,
      anon_sym_LT_BANG,
    ACTIONS(68), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(71), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    ACTIONS(80), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(7), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [300] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(11), 1,
      anon_sym_LT_PERCENT_POUND,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(76), 1,
      sym_style_start_tag,
    STATE(77), 1,
      sym_script_start_tag,
    STATE(6), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_template,
      sym_comment_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(87), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(91), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(95), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(99), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(103), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(107), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(115), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(119), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(123), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(127), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(131), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(135), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(139), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [558] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(143), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(111), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(147), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [663] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [693] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [708] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(151), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [753] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(99), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [798] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [813] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_LT_PERCENT,
      anon_sym_LT,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_PERCENT_POUND,
      anon_sym_LT_SLASH,
      sym_text,
  [828] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(51), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat2,
  [845] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(163), 1,
      anon_sym_SLASH_GT,
    ACTIONS(165), 1,
      sym_attribute_name,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [862] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(169), 1,
      anon_sym_SQUOTE,
    ACTIONS(171), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(50), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat1,
  [879] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    ACTIONS(175), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(45), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat2,
  [896] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(45), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat2,
  [913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_attribute_name,
    ACTIONS(185), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [928] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(190), 1,
      anon_sym_GT,
    ACTIONS(192), 1,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [945] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(190), 1,
      anon_sym_GT,
    ACTIONS(194), 1,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [962] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(199), 1,
      anon_sym_SQUOTE,
    ACTIONS(201), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(49), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat1,
  [979] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(173), 1,
      anon_sym_SQUOTE,
    ACTIONS(204), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(49), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat1,
  [996] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(175), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(206), 1,
      anon_sym_DQUOTE,
    STATE(45), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat2,
  [1013] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    ACTIONS(208), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(44), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat2,
  [1030] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(204), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(206), 1,
      anon_sym_SQUOTE,
    STATE(49), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat1,
  [1047] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(210), 1,
      anon_sym_SLASH_GT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1064] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(212), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(53), 2,
      sym_template,
      aux_sym_quoted_attribute_value_repeat1,
  [1081] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_EQ,
    ACTIONS(214), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1093] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_GT,
    ACTIONS(220), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_attribute_name,
    ACTIONS(222), 1,
      anon_sym_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1121] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_GT,
    ACTIONS(224), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1135] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_attribute_name,
    ACTIONS(227), 1,
      anon_sym_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1149] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_attribute_value,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_quoted_attribute_value,
  [1165] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_attribute_name,
    ACTIONS(235), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1179] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_attribute_value,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    ACTIONS(241), 1,
      anon_sym_DQUOTE,
    STATE(70), 1,
      sym_quoted_attribute_value,
  [1195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1204] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(137), 2,
      anon_sym_LT_PERCENT,
      anon_sym_SQUOTE,
  [1215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      sym_raw_text,
    STATE(22), 1,
      sym_end_tag,
  [1237] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    ACTIONS(251), 1,
      sym_raw_text,
    STATE(9), 1,
      sym_end_tag,
  [1250] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym__start_tag_name,
    ACTIONS(255), 1,
      sym__script_start_tag_name,
    ACTIONS(257), 1,
      sym__style_start_tag_name,
  [1263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(105), 2,
      anon_sym_LT_PERCENT,
      anon_sym_SQUOTE,
  [1283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_EQ,
    ACTIONS(214), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1294] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym__script_start_tag_name,
    ACTIONS(257), 1,
      sym__style_start_tag_name,
    ACTIONS(263), 1,
      sym__start_tag_name,
  [1307] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(137), 2,
      anon_sym_LT_PERCENT,
      anon_sym_DQUOTE,
  [1318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(105), 2,
      anon_sym_LT_PERCENT,
      anon_sym_DQUOTE,
  [1329] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    ACTIONS(267), 1,
      sym_raw_text,
    STATE(30), 1,
      sym_end_tag,
  [1342] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    ACTIONS(269), 1,
      sym_raw_text,
    STATE(28), 1,
      sym_end_tag,
  [1355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      aux_sym_template_token1,
    ACTIONS(275), 1,
      aux_sym_template_token2,
  [1373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      aux_sym_template_token1,
    ACTIONS(279), 1,
      aux_sym_template_token2,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1391] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__end_tag_name,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
  [1401] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_end_tag,
  [1435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(287), 1,
      sym__end_tag_name,
  [1445] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_template_token1,
    ACTIONS(291), 1,
      aux_sym_template_token2,
  [1465] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    STATE(38), 1,
      sym_end_tag,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    STATE(16), 1,
      sym_end_tag,
  [1501] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      aux_sym_template_token1,
    ACTIONS(299), 1,
      aux_sym_template_token2,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_GT,
  [1518] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_GT,
  [1525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_PERCENT_GT,
  [1532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_PERCENT_GT,
  [1539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym__doctype,
  [1546] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_GT,
  [1553] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_PERCENT_GT,
  [1560] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_GT,
  [1567] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_GT,
  [1574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_PERCENT_GT,
  [1581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym__end_tag_name,
  [1588] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_GT,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_PERCENT_GT,
  [1602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_PERCENT_GT,
  [1609] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_PERCENT_GT,
  [1616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_PERCENT_GT,
  [1623] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_PERCENT_GT,
  [1630] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_PERCENT_GT,
  [1637] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      aux_sym_template_token2,
  [1644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      aux_sym_template_token2,
  [1651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      aux_sym_doctype_token1,
  [1658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_erroneous_end_tag_name,
  [1665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      aux_sym_doctype_token1,
  [1672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      aux_sym_template_token2,
  [1679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      ts_builtin_sym_end,
  [1686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__end_tag_name,
  [1693] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_erroneous_end_tag_name,
  [1700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      aux_sym_template_token2,
  [1707] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      aux_sym_template_token2,
  [1714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      aux_sym_template_token2,
  [1721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 252,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 348,
  [SMALL_STATE(10)] = 363,
  [SMALL_STATE(11)] = 378,
  [SMALL_STATE(12)] = 393,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 438,
  [SMALL_STATE(16)] = 453,
  [SMALL_STATE(17)] = 468,
  [SMALL_STATE(18)] = 483,
  [SMALL_STATE(19)] = 498,
  [SMALL_STATE(20)] = 513,
  [SMALL_STATE(21)] = 528,
  [SMALL_STATE(22)] = 543,
  [SMALL_STATE(23)] = 558,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 588,
  [SMALL_STATE(26)] = 603,
  [SMALL_STATE(27)] = 618,
  [SMALL_STATE(28)] = 633,
  [SMALL_STATE(29)] = 648,
  [SMALL_STATE(30)] = 663,
  [SMALL_STATE(31)] = 678,
  [SMALL_STATE(32)] = 693,
  [SMALL_STATE(33)] = 708,
  [SMALL_STATE(34)] = 723,
  [SMALL_STATE(35)] = 738,
  [SMALL_STATE(36)] = 753,
  [SMALL_STATE(37)] = 768,
  [SMALL_STATE(38)] = 783,
  [SMALL_STATE(39)] = 798,
  [SMALL_STATE(40)] = 813,
  [SMALL_STATE(41)] = 828,
  [SMALL_STATE(42)] = 845,
  [SMALL_STATE(43)] = 862,
  [SMALL_STATE(44)] = 879,
  [SMALL_STATE(45)] = 896,
  [SMALL_STATE(46)] = 913,
  [SMALL_STATE(47)] = 928,
  [SMALL_STATE(48)] = 945,
  [SMALL_STATE(49)] = 962,
  [SMALL_STATE(50)] = 979,
  [SMALL_STATE(51)] = 996,
  [SMALL_STATE(52)] = 1013,
  [SMALL_STATE(53)] = 1030,
  [SMALL_STATE(54)] = 1047,
  [SMALL_STATE(55)] = 1064,
  [SMALL_STATE(56)] = 1081,
  [SMALL_STATE(57)] = 1093,
  [SMALL_STATE(58)] = 1107,
  [SMALL_STATE(59)] = 1121,
  [SMALL_STATE(60)] = 1135,
  [SMALL_STATE(61)] = 1149,
  [SMALL_STATE(62)] = 1165,
  [SMALL_STATE(63)] = 1179,
  [SMALL_STATE(64)] = 1195,
  [SMALL_STATE(65)] = 1204,
  [SMALL_STATE(66)] = 1215,
  [SMALL_STATE(67)] = 1224,
  [SMALL_STATE(68)] = 1237,
  [SMALL_STATE(69)] = 1250,
  [SMALL_STATE(70)] = 1263,
  [SMALL_STATE(71)] = 1272,
  [SMALL_STATE(72)] = 1283,
  [SMALL_STATE(73)] = 1294,
  [SMALL_STATE(74)] = 1307,
  [SMALL_STATE(75)] = 1318,
  [SMALL_STATE(76)] = 1329,
  [SMALL_STATE(77)] = 1342,
  [SMALL_STATE(78)] = 1355,
  [SMALL_STATE(79)] = 1363,
  [SMALL_STATE(80)] = 1373,
  [SMALL_STATE(81)] = 1383,
  [SMALL_STATE(82)] = 1391,
  [SMALL_STATE(83)] = 1401,
  [SMALL_STATE(84)] = 1409,
  [SMALL_STATE(85)] = 1417,
  [SMALL_STATE(86)] = 1425,
  [SMALL_STATE(87)] = 1435,
  [SMALL_STATE(88)] = 1445,
  [SMALL_STATE(89)] = 1455,
  [SMALL_STATE(90)] = 1465,
  [SMALL_STATE(91)] = 1475,
  [SMALL_STATE(92)] = 1483,
  [SMALL_STATE(93)] = 1491,
  [SMALL_STATE(94)] = 1501,
  [SMALL_STATE(95)] = 1511,
  [SMALL_STATE(96)] = 1518,
  [SMALL_STATE(97)] = 1525,
  [SMALL_STATE(98)] = 1532,
  [SMALL_STATE(99)] = 1539,
  [SMALL_STATE(100)] = 1546,
  [SMALL_STATE(101)] = 1553,
  [SMALL_STATE(102)] = 1560,
  [SMALL_STATE(103)] = 1567,
  [SMALL_STATE(104)] = 1574,
  [SMALL_STATE(105)] = 1581,
  [SMALL_STATE(106)] = 1588,
  [SMALL_STATE(107)] = 1595,
  [SMALL_STATE(108)] = 1602,
  [SMALL_STATE(109)] = 1609,
  [SMALL_STATE(110)] = 1616,
  [SMALL_STATE(111)] = 1623,
  [SMALL_STATE(112)] = 1630,
  [SMALL_STATE(113)] = 1637,
  [SMALL_STATE(114)] = 1644,
  [SMALL_STATE(115)] = 1651,
  [SMALL_STATE(116)] = 1658,
  [SMALL_STATE(117)] = 1665,
  [SMALL_STATE(118)] = 1672,
  [SMALL_STATE(119)] = 1679,
  [SMALL_STATE(120)] = 1686,
  [SMALL_STATE(121)] = 1693,
  [SMALL_STATE(122)] = 1700,
  [SMALL_STATE(123)] = 1707,
  [SMALL_STATE(124)] = 1714,
  [SMALL_STATE(125)] = 1721,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(99),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(94),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(123),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(73),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(121),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(125),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(79),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(114),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(69),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(116),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2), SHIFT_REPEAT(80),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2), SHIFT_REPEAT(45),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(56),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [196] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2), SHIFT_REPEAT(89),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2), SHIFT_REPEAT(49),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(72),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [345] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_eex_external_scanner_create(void);
void tree_sitter_html_eex_external_scanner_destroy(void *);
bool tree_sitter_html_eex_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_eex_external_scanner_serialize(void *, char *);
void tree_sitter_html_eex_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html_eex(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_eex_external_scanner_create,
      tree_sitter_html_eex_external_scanner_destroy,
      tree_sitter_html_eex_external_scanner_scan,
      tree_sitter_html_eex_external_scanner_serialize,
      tree_sitter_html_eex_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
